name: My First workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
    
        - name: Welcome messsage
          run: | 
            chmod +x script.sh  
            ./script.sh
            

        # - name: List Files
        #   run: ls

        # - name: Read Files
        #   run: cat README.md
